### Customer register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "Muhammet",
  "email": "m@gmail.com",
  "password": "123",
  "phone": "5555555555",
  "role": "customer",
  "city": "Ankara",
  "district": "Çankaya",
  "address": "1596.Cadde NO:24D"
}




### Login Request
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "m@gmail.com",
  "password": "1234567890"
}

### Login Request
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "kebapci@example.com",
  "password": "kebap123"
}



### Get Profile (Customer)
GET http://localhost:8080/api/profile
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA


### Get Profile (restaurant)
GET http://localhost:8080/api/profile
Authorization: Bearer   eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZWJhcGNpQGV4YW1wbGUuY29tIiwicm9sZSI6InJlc3RhdXJhbnRfb3duZXIiLCJpZCI6ImFkNWMxZjQ1LTAzY2QtNDY4Ni1hZDYwLTc2ZWI4YWEwMTU4ZiIsImlhdCI6MTc0NDMwNTQxNSwiZXhwIjoxNzQ0MzIzNDE1fQ.cugQkxH_PVWAzA5ne3D1qzmygC9LprmjVD5P7ojeLu0

### Logout
POST http://localhost:8080/api/logout
Authorization: Bearer     eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNDMxOTk3YmMtNzA4Yi00ZjFmLWI0YzUtZGVhOWJlNWFjZGE3IiwiaWF0IjoxNzQzNjE4NDU1LCJleHAiOjE3NDM2MzY0NTV9.LprDWVFncBMWk6YJSsuPr-PJxQKqHmK1rz1Ygvut9PU


### Forgot Password
POST http://localhost:8080/api/forgot-password
Content-Type: application/json

{
  "email": "muhammetcetinalp35@gmail.com"
}



### Register a test restaurant
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "Test Burger 3",
  "email": "testburger3@example.com",
  "password": "123456",
  "phone": "5551000001",
  "role": "restaurant_owner",
  "city": "İstanbul",
  "district": "Kadıköy",
  "address": "Deneme Sokak No:1",
  "businessHoursStart": "11:00",
  "businessHoursEnd": "23:00",
  "cuisineType": "fastfood",
  "deliveryType": "PICKUP"
}

### Search for restaurants by keyword (public)
GET http://localhost:8080/api/public/search-restaurants



### Search for oepn restaurants
GET http://localhost:8080/api/public/search-restaurants?keyword=kebap&sortBy=rating


### Logout (dummy, for client-side use only)
POST http://localhost:8080/api/logout
Authorization: Bearer     eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0MzM4NzAxOCwiZXhwIjoxNzQzNDA1MDE4fQ.qx-YjhHWDtkmSG2eMv54uDjq1M2iMpY64RClnJ7OUMY


###
GET http://localhost:8080/api/public/search-restaurants?cuisineType=turkish

###
GET http://localhost:8080/api/public/search-restaurants?deliveryType=both

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "Kebapçı Hakkı",
  "email": "kebapci3@example.com",
  "password": "kebap123",
  "phone": "5551000103",
  "role": "restaurant_owner",
  "city": "Istanbul",
  "district": "Fatih",
  "address": "Divan Yolu 42",
  "businessHoursStart": "10:00",
  "businessHoursEnd": "23:59",
  "cuisineType": "turkish",
  "deliveryType": "PICKUP"
}

###
GET http://localhost:8080/api/public/search-restaurants?topRated=4.9


###
GET http://localhost:8080/api/public/search-restaurants


### Favori restaurant ekleme
POST http://localhost:8080/api/profile/favorites/add?restaurantId=ad5c1f45-03cd-4686-ad60-76eb8aa0158f
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA


### favori restoranları görme
GET http://localhost:8080/api/profile/favorites
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

### favori restaurant çıakrtma isteği
DELETE http://localhost:8080/api/profile/favorites/remove?restaurantId=caa3a901-33b8-47e6-ac88-ccbecd5b9e7d
Authorization: Bearer        eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0MzQ1OTM2NCwiZXhwIjoxNzQzNDc3MzY0fQ.u4082bY98Pkp-yxTRxgfI45Vq0ZcIyQYjIXNL-2FOII





### Show Basket
GET http://localhost:8080/api/cart/showcart
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

###
POST http://localhost:8080/api/cart/add?menuItemId=5&quantity=1
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA


### create order with credit card
POST http://localhost:8080/api/orders/create?deliveryAddress=Ankara&paymentMethod=CREDIT_CARD&deliveryType=DELIVERY&tipAmount=20.0
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA
Content-Type: application/json

{
  "cardNumber": "1234567812345678",
  "expiryDate": "12/26",
  "cvv": "123"
}

### create order with  cash
POST http://localhost:8080/api/orders/create?deliveryAddress=DenemeAdres&paymentMethod=CASH&deliveryType=DELIVERY
Content-Type: application/json
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

{
}

### show past orders
GET http://localhost:8080/api/orders/history
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA




### delete from basket
DELETE http://localhost:8080/api/orders/remove?menuItemId=3
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

### Show Basket
GET http://localhost:8080/api/cart/showcart
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

### delete all
DELETE http://localhost:8080/api/orders/remove-all?menuItemId=4
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA

###
POST http://localhost:8080/api/feedback/submit
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiYjg3MTYyOWEtYjliMC00YTU0LTkzMTEtZWU1YzFjMzk5ZDNkIiwiaWF0IjoxNzQzNjI0MzgxLCJleHAiOjE3NDM2NDIzODF9.vbKOYZVWssdxmHkTGWClj-UKmJILW0tlCqofbNsHMvo
Content-Type: application/json

{
  "orderId": "order-843e530d-3ed4-43a6-8475-f77b2b01a885",
  "targetId": "courier-123abc",
  "targetType": "COURIER",
  "rating": 5,
  "comment": "Çok hızlı ve güler yüzlüydü!"
}

###
POST http://localhost:8080/api/feedback/submit
Authorization: Bearer    eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlkIjoiNGE5MDY4OTEtZDAyOC00YmQ5LWEwYjItNmQ3YTMxN2NiYWFlIiwiaWF0IjoxNzQ0MzAwMTY3LCJleHAiOjE3NDQzMTgxNjd9.RWMBAVzfISb-nTT7_CDSdtYWj52asaheH12FHUHKofA
Content-Type: application/json

{
  "orderId": "order-9a6568bd-f2bb-4206-9643-e009fec91c71",
  "targetId": "ad5c1f45-03cd-4686-ad60-76eb8aa0158f",
  "targetType": "RESTAURANT",
  "rating": 4,
  "comment": "Yemekler sıcaktı ama biraz geç geldi."
}

#### restorana menü ekleme
POST http://localhost:8080/api/restaurants/ad5c1f45-03cd-4686-ad60-76eb8aa0158f/menu
Content-Type: application/json
Authorization: Bearer   eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZWJhcGNpQGV4YW1wbGUuY29tIiwicm9sZSI6InJlc3RhdXJhbnRfb3duZXIiLCJpZCI6ImFkNWMxZjQ1LTAzY2QtNDY4Ni1hZDYwLTc2ZWI4YWEwMTU4ZiIsImlhdCI6MTc0NDMwNTQxNSwiZXhwIjoxNzQ0MzIzNDE1fQ.cugQkxH_PVWAzA5ne3D1qzmygC9LprmjVD5P7ojeLu0

{
  "name": "Spaghetti Bolognese",
  "description": "Traditional Italian pasta with meat sauce",
  "price": 120.50,
  "available": true
}


###get restaurant past orders
GET http://localhost:8080/api/orders/history/restaurant/44f3fd7d-dc8c-42fc-b106-80e8958a383b
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZWJhcGNpQGV4YW1wbGUuY29tIiwicm9sZSI6InJlc3RhdXJhbnRfb3duZXIiLCJpZCI6IjQ0ZjNmZDdkLWRjOGMtNDJmYy1iMTA2LTgwZTg5NThhMzgzYiIsImlhdCI6MTc0NDMyMzQ5NiwiZXhwIjoxNzQ0MzQxNDk2fQ.x3EKKl5_cu-rcXT3dDbIJ3KLIGAbsSXDgmTRrWAAhO0



###get statu of restaruant
PATCH http://localhost:8080/api/restaurants/88241f28-ecec-467a-b363-a527e9f31e20/toggle-status
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZWJhcGNpQGV4YW1wbGUuY29tIiwicm9sZSI6InJlc3RhdXJhbnRfb3duZXIiLCJpZCI6IjQ0ZjNmZDdkLWRjOGMtNDJmYy1iMTA2LTgwZTg5NThhMzgzYiIsImlhdCI6MTc0NDMyMzQ5NiwiZXhwIjoxNzQ0MzQxNDk2fQ.x3EKKl5_cu-rcXT3dDbIJ3KLIGAbsSXDgmTRrWAAhO0
